### PR TITLE
Merge Qwant & Geocoders's master branch

### LINKED ISSUE #4: Merge the forks
Hey,

we need to exterminate the forks and use the same geocoder-tester repo for all our tests on Mimir \o/

exterminate !

Some of your tests won't be usable for us and the [geocoders](http://github.com/geocoders) community:
* your Paris tests are too specific (there are a few other Paris in the world more relevant than "Le Touquet-Paris-Plage")
* your tests on NPDC stop areas are great, but "Bourg" and "Terrasse" will never actually work for anyone

I can see 3 solutions:
* re-work on your specific tests so anyone can use them, and recontribute them to the original repo
* dont change your test but rebase regularly to keep this repo up to date
* split the repo to isolate your specific tests, then make some magic so we can launch the tests from both this repo and your specific repo. @antoine-de will give you some tips on that :wink:

### PR DESCRIPTION
**Pull request by nonifier**
In order to fix https://github.com/CanalTP/geocoder-tester/issues/4,
we first want to merge the two repos Qwant & Geocoders back-in before discussing the next steps.

This PR brings the repo up to date with both master branches.

### CODE REVIEW

**Comment by nlehuby** [comment]
:scream_cat:

**Comment by nonifier** [comment]
@nlehuby: not sure whether this makes you happy or scared to death....

**Comment by nlehuby** [comment]
I was happy when I received the github notifications, then, I saw the endless list of commits ...

How do you plan to merge this ?

**Comment by nonifier** [comment]
> How do you plan to merge this ?

I ran our test suite (we only test at most against France's dataset) with the following results :

|		| failures		| skipped			| total tests
|--- 	| ---			| --- 				| ---
|Before	| 2,127 (±0) 	| 1 skipped (±0)	| 12,192 (+0)
|After 	| 2,245 (+118)	| 7 skipped (+6)	| 12,344 (+152)

Edit: In the +118 failures, 109 are related to our `nordpasdecalais.test_stop_areas.csv` file which doesn't seem to be picked-up properly. Which leaves +9 new failures if we disregard the file.  

The results are within the same order of magnitude as before. I don't thing I could go throw all the new failures () to make sure they are all relevant as we only are interested in result trends to validate our work. Hence this seems perfectly fine to me to be merged.

**Comment by nonifier** [comment]
@kinnou02 is about to cut my fingers :dagger: :D 
No one will ever read my PR anyway :see_no_evil:

**Pull request merged**
